# Generated by Django 4.2.1 on 2023-05-18 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Sin empezar'), (1, 'En curso'), (2, 'Finalizado'), (3, 'Validado')])),
                ('orden', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Sin empezar'), (1, 'En curso'), (2, 'Finalizado'), (3, 'Validado')])),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField(choices=[(0, 'Observador'), (1, 'Trabajador'), (2, 'Validador')])),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.paso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paso',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='proyectos.proyecto'),
        ),
    ]
