# Generated by Django 4.2.1 on 2023-05-18 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No validado'), (1, 'Validado')], default=0),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='paso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paso',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin empezar'), (1, 'En curso'), (2, 'Finalizado'), (3, 'Validado')], default=0),
        ),
        migrations.AlterField(
            model_name='paso',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin empezar'), (1, 'En curso'), (2, 'Finalizado'), (3, 'Validado')], default=0),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='paso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.paso'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rol',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Observador'), (1, 'Trabajador'), (2, 'Validador')], null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
