# Generated by Django 4.2.1 on 2023-05-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_paso_nombre_trabajador_estado_trabajador_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='proyectos.proyecto'),
        ),
    ]
