# Generated by Django 4.2.1 on 2023-05-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_trabajador_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paso',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='paso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='proyectos.paso'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
    ]
